stages:
  - build
  - deploy

build:
  stage: build
  image: archlinux:latest
  before_script:
    - pacman-key --init
    - echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
    - pacman -Syu --noconfirm base-devel wine meson mingw-w64-toolchain mingw-w64 glslang vulkan-headers git
  script:
    - ./prepare.sh
    - ./build-master.sh --deploy-web

pages:
  stage: deploy
  script:
    - mkdir -p ./public/
    - mv -v ./build/web/* ./public/
  artifacts:
    paths:
      - public
