name: Artifacts (Package)

on: [push, pull_request, workflow_dispatch]

jobs:
  build-artifacts:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup problem matcher
      uses: Joshua-Ashton/gcc-problem-matcher@v1

    - name: Build release
      id: build-release
      uses: Joshua-Ashton/arch-mingw-github-action@v7
      with:
        command: |
          pacman -Syu --noconfirm git
          ./prepare.sh
          . ./build-master.sh --github
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Create releases
      id: create-releases
      uses: softprops/action-gh-release@v1
      with:
        name: "DXVK Async Automated Build"
        tag_name: ${{ env.PACKAGE_NAME }}
        body_path: INFO.md
        fail_on_unmatched_files: true
        files: |
          ./build/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}